package pl.elka.gis.logic;

public enum ResultFlag {
    PREPROCESSING_ERROR_GENERAL,
    PREPROCESSING_DONE_CENTERS_MORE_OR_EQUAL_VERTEXES,
    PREPROCESSING_DONE_ERR_TOO_MANY_SUBGRAPHS,
    PREPROCESSING_DONE_ERR_NO_VERTEXES,
    PREPROCESSING_DONE_ERR_NO_CENTERS,
    PREPROCESSING_DONE_CENTERS_EQUAL_SUBGRAPHS,
    PREPROCESSING_DONE_NO_EDGE_CASE_FOUND
}
